#parameters
snakemake_dir_path: '/srv/public/users/brown/pipelines/assembly/snakemake/5.Decontamination/'
nt_dbDir: '/srv/public/users/brown/db/nt/' # Directory containing ncbi nt database
lr: '/srv/public/users/brown/pipelines/assembly/snakemake/5.Decontamination/lr.fofn'
read_type: 'hifi' #Possible options: hifi, ont, clr
prim_asm: '/srv/public/users/brown/pipelines/assembly/snakemake/5.Decontamination/assembly.fasta'
threads: 40
